### ISSUE TITLE
Update bbox return on search & count report

### ISSUE THREAD

**Issue by richardjr** [nautoguide/locaria#305]
Both the report search_counts and search method need to return a bbox that is for the 'limit' not the 'display_limit'

```{"queue":"searchFeatures","api":"api","data":{"category":"Activities","search_text":"","bbox_srid":"4326","method":"report","report_name":"search_counts","location":"SRID=4326;POINT(-1.77539 51.53941)","location_distance":19000,"display_limit":20,"offset":0},"uuid":"2b0e1e65-b220-4ae8-bdc1-817274baa5cc"}```

**Comment by citizenfish** [comment]
This has been done in search.sql NOTE WELL that the BBOX does not compute correctly in cluster mode which will need thinking about.
